# Generated by Django 4.1 on 2022-10-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ichki',
            name='bolim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ichki_bolimlar', to='asosiy.bolim'),
        ),
    ]
