# Generated by Django 4.1 on 2022-10-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtmaapp', '0003_rename_pofil_buyurtma_profil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savat',
            old_name='profile',
            new_name='profil',
        ),
        migrations.RenameField(
            model_name='tanlangan',
            old_name='profile',
            new_name='profil',
        ),
    ]
